exports.mercClass = [
  { name: "ARTIFICER" },
  { name: "BARD" },
  { name: "BLOOD HUNTER" },
  { name: "CLERIC" },
  { name: "DRUID" },
  { name: "FURY FIGHTER" },
  { name: "MARTIAL ARTIST" },
  { name: "SORCERER" },
  { name: "PALADIN" },
  { name: "RANGER" },
  { name: "ROGUE" },
  { name: "SORCERER" },
  { name: "WARLOCK" },
  { name: "WIZARD" },
];
